### ISSUE TITLE
[爬虫相关]统一身份认证页面的登录加密是如何解决的？

### ISSUE THREAD

**Issue by Vizards** [UESTC-Miniapp/UESTC-Miniapp-FrontEnd#29]
如题，不知道何时更新的，现在：

- 统一身份认证页面的 JavaScript 开始被加密，而且加密方式猜不出来；
- 登录 POST 请求的请求体也被加密了；

顺便 @MrThanlon 后端大佬，是否有解决方案？

**Comment by Yidadaa** [comment]
woc，刚刚去看了一下，这加密也太狠了，建议还是 [Puppeteer](https://github.com/GoogleChrome/puppeteer) 一波流吧。

**Comment by MrThanlon** [comment]
考虑[nightmare](https://github.com/segmentio/nightmare)
后端很久没更新了，我也不太确定

**Comment by Vizards** [comment]
在服务端模拟浏览器的成本还是太高了，如果不能破解加密的话，最优的解决方案可能还是把登录页面套一个 webview 放进客户端，然后回传登录之后的 Cookie ...

**Comment by Yidadaa** [comment]
那小程序就很难受了，大概搜了一下，puppeteer 优化一下，普通机器还是能跑到 100QPS 的，应付平常使用应该是够了
